eureka:
  client:
    serviceUrl:
      defaultZone: http://zhangbin:password@localhost:8761/eureka/
      region: default
      registryFetchIntervalSeconds: 5
  instance:
    hostname: localhost

server:
  port: 9411
spring:
  application:
    name: service-zipkin
