eureka:
  client:
    serviceUrl:
      defaultZone: http://zhangbin:password@localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 8763
spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0