eureka:
  client:
    serviceUrl:
      defaultZone: http://zhangbin:password@localhost:8761/eureka/
server:
  port: 8000
spring:
  application:
    name: service-zuul

#security:
#  basic:
#    enabled: true
#  user:
#    name: zhangbin
#    password: password
#

zuul:
  routes:
    ribbon:
      path: /ribbon/**
      serviceId: service-ribbon
    feign:
      path: /feign/**
      serviceId: service-feign
    hi:
      path: /hi/**
      serviceId: service-hi